version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: quiltshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: quiltshop
      MYSQL_USER: quilt
      MYSQL_PASSWORD: QuiltPass123!
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dbdata:
